services:
  stats-server:
    build: stats/server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: postgresql-ewm-stats-db
    ports:
      - "6532:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  #  ewm-service:
  #    build: main-service
  #    container_name: main-service
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      - CLIENT_URL=http://stats-server:9090
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:7832/ewm-main
  #      - SPRING_DATASOURCE_USERNAME=dbuser
  #      - SPRING_DATASOURCE_PASSWORD=12345

  ewm-db:
    image: postgres:16.1
    container_name: postgresql-ewm-main-db
    ports:
      - "7832:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
